"""HCM causal estimation: formula-driven dispatch from identified do-calculus expressions."""

from .causal_estimators import (
    ConditionalDensityEstimator,
    SubunitParamEstimator,
    QDensityEstimator,
    ast_to_estimator,
    estimate_causal_effect,
    SUPPORTED_FAMILIES,
)
from .parallel import ParallelBackend, parallel_map
from .per_unit import (
    aggregate_per_unit_outputs,
    device_kwargs_for_workers,
    estimate_ate_confounder,
    estimate_ate_confounder_torch_batched,
    fit_per_unit_estimators,
    fit_regressors_per_unit,
    fit_torch_batched_regressor_per_unit,
)
from .torch_estimators import (
    MLPRegressorPerUnit,
    TorchBatchedBernoulliState,
    TorchBatchedGaussianState,
    estimate_ate_confounder_torch_batched as estimate_ate_confounder_torch_batched_low_level,
    torch_compute_subunit_params,
    torch_conditional_expectations_per_unit,
    torch_fit_batched_bernoulli,
    torch_fit_batched_gaussian,
    torch_predict_batched_bernoulli,
    torch_predict_batched_gaussian,
)
from .econometric_estimators import (
    RegressionResult,
    OLSModelSpec,
    IV2SLSResult,
    IV2SLSModelSpec,
    fit_ols,
    fit_reduced_form,
    fit_2sls,
    fit_many_ols,
    fit_many_reduced_form,
    fit_many_2sls,
)

__all__ = [
    "ConditionalDensityEstimator",
    "SubunitParamEstimator",
    "QDensityEstimator",
    "ast_to_estimator",
    "estimate_causal_effect",
    "SUPPORTED_FAMILIES",
    "ParallelBackend",
    "parallel_map",
    "fit_per_unit_estimators",
    "aggregate_per_unit_outputs",
    "fit_regressors_per_unit",
    "estimate_ate_confounder",
    "fit_torch_batched_regressor_per_unit",
    "estimate_ate_confounder_torch_batched",
    "device_kwargs_for_workers",
    "MLPRegressorPerUnit",
    "TorchBatchedGaussianState",
    "TorchBatchedBernoulliState",
    "torch_fit_batched_gaussian",
    "torch_fit_batched_bernoulli",
    "torch_predict_batched_gaussian",
    "torch_predict_batched_bernoulli",
    "torch_compute_subunit_params",
    "torch_conditional_expectations_per_unit",
    "estimate_ate_confounder_torch_batched_low_level",
    "RegressionResult",
    "OLSModelSpec",
    "IV2SLSResult",
    "IV2SLSModelSpec",
    "fit_ols",
    "fit_reduced_form",
    "fit_2sls",
    "fit_many_ols",
    "fit_many_reduced_form",
    "fit_many_2sls",
]
